In [2]:
import requests
import pandas as pd
import numpy as np

# Base URL for all FEMA API calls
BASE_URL = "https://www.fema.gov/api/open"

print("Libraries loaded successfully")
print(f"Pandas version: {pd.__version__}")
print(f"Numpy version: {np.__version__}")

Libraries loaded successfully
Pandas version: 2.3.3
Numpy version: 2.4.3

In [3]:
# Fetch Dataset 1 - Disaster Declarations Summaries

url = f"{BASE_URL}/v2/DisasterDeclarationsSummaries"

params = {
    "$top": 200,       # Fetch only 200 records for now (exploration)
    "$format": "json"  # Return data as JSON
}

# Make the API request
response = requests.get(url, params=params)

# Check if request was successful
print(f"Status Code: {response.status_code}")  # 200 = success

# Parse the JSON response
data = response.json()

# Convert to DataFrame
df_declarations = pd.DataFrame(data["DisasterDeclarationsSummaries"])

# Quick overview
print(f"Shape: {df_declarations.shape}")
print(f"\nColumn Names:")
print(df_declarations.columns.tolist())
print(f"\nFirst 3 rows:")
display(df_declarations.head(3))

Status Code: 200
Shape: (200, 28)

Column Names:
['femaDeclarationString', 'disasterNumber', 'state', 'declarationType', 'declarationDate', 'fyDeclared', 'incidentType', 'declarationTitle', 'ihProgramDeclared', 'iaProgramDeclared', 'paProgramDeclared', 'hmProgramDeclared', 'incidentBeginDate', 'incidentEndDate', 'disasterCloseoutDate', 'tribalRequest', 'fipsStateCode', 'fipsCountyCode', 'placeCode', 'designatedArea', 'declarationRequestNumber', 'lastIAFilingDate', 'incidentId', 'region', 'designatedIncidentTypes', 'lastRefresh', 'hash', 'id']

First 3 rows:

,femaDeclarationString,disasterNumber,state,declarationType,declarationDate,fyDeclared,incidentType,declarationTitle,ihProgramDeclared,iaProgramDeclared,...,placeCode,designatedArea,declarationRequestNumber,lastIAFilingDate,incidentId,region,designatedIncidentTypes,lastRefresh,hash,id
0,FM-5529-OR,5529,OR,FM,2024-08-09T00:00:00.000Z,2024,Fire,LEE FALLS FIRE,False,False,...,99067,Washington (County),24122,None,2024081001,10,R,2024-08-27T18:22:14.800Z,ae87cf3c6ed795015b714af7166c7c295b2b67c7,09e3f81a-5e16-4b72-b317-1c64e0cfa59c
1,FM-5528-OR,5528,OR,FM,2024-08-06T00:00:00.000Z,2024,Fire,ELK LANE FIRE,False,False,...,99031,Jefferson (County),24116,None,2024080701,10,R,2024-08-27T18:22:14.800Z,432cf0995c47e3895cea696ede5621b810460501,59983f89-30bf-4888-b21b-62e8d57d9aac
2,FM-5527-OR,5527,OR,FM,2024-08-02T00:00:00.000Z,2024,Fire,MILE MARKER 132 FIRE,False,False,...,99017,Deschutes (County),24111,None,2024080301,10,R,2024-08-27T18:22:14.800Z,2f21d90cb6bc64b0d4121aa3f18d852bbb4b11fa,8d13ecf0-bc2f-496b-8c9f-b2e73da832a0

In [4]:
# Inspect Dataset 1 - Disaster Declarations Summaries

print("=" * 55)
print("DATASET 1: DISASTER DECLARATIONS SUMMARIES")
print("=" * 55)

# Data types of each column
print("\n── DATA TYPES ──")
print(df_declarations.dtypes)

# Null/missing values per column
print("\n── NULL COUNTS ──")
null_counts = df_declarations.isnull().sum()
print(null_counts[null_counts > 0])  # Only show columns WITH nulls

# Incident types breakdown
print("\n── INCIDENT TYPES (What kinds of disasters?) ──")
print(df_declarations['incidentType'].value_counts())

# Declaration types breakdown
print("\n── DECLARATION TYPES ──")
print(df_declarations['declarationType'].value_counts())

# States breakdown (top 10)
print("\n── TOP 10 STATES BY DISASTER COUNT ──")
print(df_declarations['state'].value_counts().head(10))

# Date range of the data
print("\n── DATE RANGE ──")
print(f"Earliest declaration: {df_declarations['declarationDate'].min()}")
print(f"Latest declaration:   {df_declarations['declarationDate'].max()}")

# Key columns preview
print("\n── KEY COLUMNS PREVIEW ──")
key_cols = ['disasterNumber', 'state', 'incidentType', 
            'declarationDate', 'incidentBeginDate', 
            'incidentEndDate', 'declarationType']
display(df_declarations[key_cols].head(5))

=======================================================
DATASET 1: DISASTER DECLARATIONS SUMMARIES
=======================================================

── DATA TYPES ──
femaDeclarationString       object
disasterNumber               int64
state                       object
declarationType             object
declarationDate             object
fyDeclared                   int64
incidentType                object
declarationTitle            object
ihProgramDeclared             bool
iaProgramDeclared             bool
paProgramDeclared             bool
hmProgramDeclared             bool
incidentBeginDate           object
incidentEndDate             object
disasterCloseoutDate        object
tribalRequest                 bool
fipsStateCode               object
fipsCountyCode              object
placeCode                   object
designatedArea              object
declarationRequestNumber    object
lastIAFilingDate            object
incidentId                  object
region                       int64
designatedIncidentTypes     object
lastRefresh                 object
hash                        object
id                          object
dtype: object

── NULL COUNTS ──
incidentEndDate             38
disasterCloseoutDate       159
lastIAFilingDate           200
designatedIncidentTypes    146
dtype: int64

── INCIDENT TYPES (What kinds of disasters?) ──
incidentType
Fire            171
Severe Storm     29
Name: count, dtype: int64

── DECLARATION TYPES ──
declarationType
FM    171
DR     29
Name: count, dtype: int64

── TOP 10 STATES BY DISASTER COUNT ──
state
OR    42
AL    28
WA    28
CA    17
TX    12
NM    11
MT     8
AZ     6
ID     6
HI     6
Name: count, dtype: int64

── DATE RANGE ──
Earliest declaration: 2016-01-21T00:00:00.000Z
Latest declaration:   2024-08-09T00:00:00.000Z

── KEY COLUMNS PREVIEW ──

,disasterNumber,state,incidentType,declarationDate,incidentBeginDate,incidentEndDate,declarationType
0,5529,OR,Fire,2024-08-09T00:00:00.000Z,2024-08-08T00:00:00.000Z,None,FM
1,5528,OR,Fire,2024-08-06T00:00:00.000Z,2024-08-04T00:00:00.000Z,None,FM
2,5527,OR,Fire,2024-08-02T00:00:00.000Z,2024-08-02T00:00:00.000Z,None,FM
3,4312,CA,Severe Storm,2017-05-02T00:00:00.000Z,2017-02-08T00:00:00.000Z,2017-02-11T00:00:00.000Z,DR
4,4251,AL,Severe Storm,2016-01-21T00:00:00.000Z,2015-12-23T00:00:00.000Z,2015-12-31T00:00:00.000Z,DR

In [6]:
# ── Check exact column names returned by the API ──
print("Actual columns in Dataset 2:")
for col in df_pa.columns.tolist():
    print(f"  - {col}")

Actual columns in Dataset 2:
  - disasterNumber
  - declarationDate
  - incidentType
  - pwNumber
  - applicationTitle
  - applicantId
  - damageCategoryCode
  - damageCategoryDescrip
  - projectStatus
  - projectProcessStep
  - projectSize
  - county
  - countyCode
  - stateAbbreviation
  - stateNumberCode
  - projectAmount
  - federalShareObligated
  - totalObligated
  - lastObligationDate
  - firstObligationDate
  - mitigationAmount
  - gmProjectId
  - gmApplicantId
  - lastRefresh
  - hash

In [7]:
# CELL 4: Inspect Dataset 2 - Public Assistance Funded Projects

print("=" * 55)
print("DATASET 2: PUBLIC ASSISTANCE FUNDED PROJECTS")
print("=" * 55)

print(f"Shape: {df_pa.shape}")

# Null counts
print("\n── NULL COUNTS ──")
null_counts2 = df_pa.isnull().sum()
print(null_counts2[null_counts2 > 0] if null_counts2.sum() > 0 else "No nulls found")

# The correct money columns
print("\n── FEDERAL SHARE OBLIGATED STATISTICS ──")
df_pa['federalShareObligated'] = pd.to_numeric(df_pa['federalShareObligated'], errors='coerce')
print(df_pa['federalShareObligated'].describe())

print("\n── TOTAL OBLIGATED STATISTICS ──")
df_pa['totalObligated'] = pd.to_numeric(df_pa['totalObligated'], errors='coerce')
print(df_pa['totalObligated'].describe())

# Project size breakdown
print("\n── PROJECT SIZE BREAKDOWN ──")
print(df_pa['projectSize'].value_counts())

# Project status breakdown
print("\n── PROJECT STATUS ──")
print(df_pa['projectStatus'].value_counts())

# Damage category breakdown
print("\n── DAMAGE CATEGORIES ──")
print(df_pa['damageCategoryDescrip'].value_counts())

# Join key check
print("\n── SAMPLE DISASTER NUMBERS (Join Key) ──")
print(df_pa['disasterNumber'].head(10).tolist())

# Key columns preview
print("\n── KEY COLUMNS PREVIEW ──")
key_cols2 = ['disasterNumber', 'stateAbbreviation', 'incidentType',
             'federalShareObligated', 'totalObligated', 
             'damageCategoryDescrip', 'projectSize']
display(df_pa[key_cols2].head(8))

=======================================================
DATASET 2: PUBLIC ASSISTANCE FUNDED PROJECTS
=======================================================
Shape: (200, 25)

── NULL COUNTS ──
county    10
dtype: int64

── FEDERAL SHARE OBLIGATED STATISTICS ──
count    2.000000e+02
mean     3.116655e+05
std      2.560190e+06
min      2.115400e+02
25%      6.712708e+03
50%      1.931884e+04
75%      6.354471e+04
max      3.118472e+07
Name: federalShareObligated, dtype: float64

── TOTAL OBLIGATED STATISTICS ──
count    2.000000e+02
mean     3.129336e+05
std      2.566909e+06
min      2.115400e+02
25%      7.008833e+03
50%      1.931884e+04
75%      6.354471e+04
max      3.118472e+07
Name: totalObligated, dtype: float64

── PROJECT SIZE BREAKDOWN ──
projectSize
Small    161
Large     39
Name: count, dtype: int64

── PROJECT STATUS ──
projectStatus
Active        199
Ineligible      1
Name: count, dtype: int64

── DAMAGE CATEGORIES ──
damageCategoryDescrip
Emergency Protective Measures                      118
Roads and Bridges                                   19
Management Costs                                    16
Debris Removal                                      14
Direct Administrative Costs                         12
Parks, Recreational Facilities, and Other Items     10
Buildings and Equipment                              6
Utilities                                            5
Name: count, dtype: int64

── SAMPLE DISASTER NUMBERS (Join Key) ──
[1239, 1239, 1239, 1603, 1239, 1239, 1239, 1239, 1239, 1239]

── KEY COLUMNS PREVIEW ──

,disasterNumber,stateAbbreviation,incidentType,federalShareObligated,totalObligated,damageCategoryDescrip,projectSize
0,1239,TX,Severe Storm(s),75000.00,80340.00,Emergency Protective Measures,Large
1,1239,TX,Severe Storm(s),14764.13,15461.00,"Parks, Recreational Facilities, and Other Items",Large
2,1239,TX,Severe Storm(s),19583.25,20507.58,"Parks, Recreational Facilities, and Other Items",Large
3,1603,LA,Hurricane,18602329.78,18788818.15,Buildings and Equipment,Large
4,1239,TX,Severe Storm(s),19688.12,20617.40,"Parks, Recreational Facilities, and Other Items",Large
5,1239,TX,Severe Storm(s),25876.88,27098.27,"Parks, Recreational Facilities, and Other Items",Large
6,1239,TX,Severe Storm(s),17808.15,18465.86,"Parks, Recreational Facilities, and Other Items",Large
7,1239,TX,Severe Storm(s),51372.25,53826.79,Buildings and Equipment,Large

In [8]:
# Fetch Dataset 3 - FEMA Web Disaster Summaries

print("=" * 55)
print("DATASET 3: FEMA WEB DISASTER SUMMARIES")
print("=" * 55)

url3 = f"{BASE_URL}/v1/FemaWebDisasterSummaries"

params3 = {
    "$top": 200,
    "$format": "json"
}

response3 = requests.get(url3, params=params3)
print(f"Status Code: {response3.status_code}")

data3 = response3.json()

# Check the exact key name in the response
print(f"\nResponse keys: {list(data3.keys())}")

# Get the correct key
key3 = [k for k in data3.keys() if k != "metadata"][0]
df_summaries = pd.DataFrame(data3[key3])

print(f"Shape: {df_summaries.shape}")

# All column names
print(f"\nAll Columns:")
for col in df_summaries.columns.tolist():
    print(f"  - {col}")

# Null counts
print("\n── NULL COUNTS ──")
null_counts3 = df_summaries.isnull().sum()
print(null_counts3[null_counts3 > 0] if null_counts3.sum() > 0 else "No nulls found")

# Key columns preview
print("\n── FIRST 5 ROWS ──")
display(df_summaries.head(5))

=======================================================
DATASET 3: FEMA WEB DISASTER SUMMARIES
=======================================================
Status Code: 200

Response keys: ['metadata', 'FemaWebDisasterSummaries']
Shape: (200, 14)

All Columns:
  - disasterNumber
  - totalNumberIaApproved
  - totalAmountIhpApproved
  - totalAmountHaApproved
  - totalAmountOnaApproved
  - totalObligatedAmountPa
  - totalObligatedAmountCatAb
  - totalObligatedAmountCatC2g
  - paLoadDate
  - iaLoadDate
  - totalObligatedAmountHmgp
  - hash
  - lastRefresh
  - id

── NULL COUNTS ──
totalNumberIaApproved         200
totalAmountIhpApproved        200
totalAmountHaApproved         200
totalAmountOnaApproved        200
totalObligatedAmountPa         47
totalObligatedAmountCatAb      63
totalObligatedAmountCatC2g    130
paLoadDate                     47
iaLoadDate                    200
totalObligatedAmountHmgp       46
dtype: int64

── FIRST 5 ROWS ──

,disasterNumber,totalNumberIaApproved,totalAmountIhpApproved,totalAmountHaApproved,totalAmountOnaApproved,totalObligatedAmountPa,totalObligatedAmountCatAb,totalObligatedAmountCatC2g,paLoadDate,iaLoadDate,totalObligatedAmountHmgp,hash,lastRefresh,id
0,3601,None,None,None,None,NaN,NaN,NaN,None,None,NaN,3de68baba960e69da445cf822d3dd859081fb34a,2023-10-09T23:02:26.341Z,faafecca-0f76-4fb8-8ffd-b6f46f3b712c
1,3602,None,None,None,None,NaN,NaN,NaN,None,None,NaN,58566c446fce5cabbd0c3412a6bb3daa4ada1993,2023-10-09T23:02:26.341Z,b74f0dc2-fab5-42b9-acf7-c94df14d85ad
2,4899,None,None,None,None,3.160623e+05,3.160623e+05,NaN,2026-03-24T00:00:00.000Z,None,0.0,da033e2e340d94186344493efc95c50f519fecbc,2026-03-24T03:21:58.128Z,553b0e21-ac27-4a14-8301-ef314f9837b4
3,1802,None,None,None,None,1.881275e+07,1.342309e+07,4.869890e+06,2026-02-06T00:00:00.000Z,None,2710679.0,d5b8865b047c2db34bae425a847682fc5c952d47,2026-02-06T02:02:06.586Z,b3ae5013-d6cc-46f3-a692-18191be44083
4,1292,None,None,None,None,2.981058e+08,1.436027e+08,1.504852e+08,2026-02-06T00:00:00.000Z,None,67665966.0,9306ff6a507ee91a18d5486db8339facdb49ddfd,2026-02-06T02:02:06.586Z,f5c3b4ea-b3fb-481b-9a3a-1c3a3508df95

In [9]:
# Verifying Join Key Across All 3 Datasets

print("=" * 55)
print("JOIN KEY VERIFICATION: disasterNumber")
print("=" * 55)

# Confirm disasterNumber exists in all 3
print("\n── COLUMN EXISTS CHECK ──")
print(f"Dataset 1 (Declarations):  {'disasterNumber' in df_declarations.columns} ✅")
print(f"Dataset 2 (PA Projects):   {'disasterNumber' in df_pa.columns} ✅")
print(f"Dataset 3 (Summaries):     {'disasterNumber' in df_summaries.columns} ✅")

# Check data types match
print("\n── DATA TYPE CHECK ──")
print(f"Dataset 1 type: {df_declarations['disasterNumber'].dtype}")
print(f"Dataset 2 type: {df_pa['disasterNumber'].dtype}")
print(f"Dataset 3 type: {df_summaries['disasterNumber'].dtype}")

# Convert all to same type for safe joining
df_declarations['disasterNumber'] = df_declarations['disasterNumber'].astype(str)
df_pa['disasterNumber'] = df_pa['disasterNumber'].astype(str)
df_summaries['disasterNumber'] = df_summaries['disasterNumber'].astype(str)

print("\n── AFTER STANDARDISATION (all converted to string) ──")
print(f"Dataset 1 type: {df_declarations['disasterNumber'].dtype}")
print(f"Dataset 2 type: {df_pa['disasterNumber'].dtype}")
print(f"Dataset 3 type: {df_summaries['disasterNumber'].dtype}")

# Check overlapping disaster numbers
common_1_2 = set(df_declarations['disasterNumber']) & set(df_pa['disasterNumber'])
common_1_3 = set(df_declarations['disasterNumber']) & set(df_summaries['disasterNumber'])
common_all = set(df_declarations['disasterNumber']) & \
             set(df_pa['disasterNumber']) & \
             set(df_summaries['disasterNumber'])

print(f"\n── OVERLAP CHECK ──")
print(f"Disasters in BOTH Dataset 1 & 2:       {len(common_1_2)}")
print(f"Disasters in BOTH Dataset 1 & 3:       {len(common_1_3)}")
print(f"Disasters in ALL 3 datasets:           {len(common_all)}")

# Sample values from each
print(f"\n── SAMPLE DISASTER NUMBERS ──")
print(f"Dataset 1: {df_declarations['disasterNumber'].head(5).tolist()}")
print(f"Dataset 2: {df_pa['disasterNumber'].head(5).tolist()}")
print(f"Dataset 3: {df_summaries['disasterNumber'].head(5).tolist()}")

=======================================================
JOIN KEY VERIFICATION: disasterNumber
=======================================================

── COLUMN EXISTS CHECK ──
Dataset 1 (Declarations):  True ✅
Dataset 2 (PA Projects):   True ✅
Dataset 3 (Summaries):     True ✅

── DATA TYPE CHECK ──
Dataset 1 type: int64
Dataset 2 type: int64
Dataset 3 type: int64

── AFTER STANDARDISATION (all converted to string) ──
Dataset 1 type: object
Dataset 2 type: object
Dataset 3 type: object

── OVERLAP CHECK ──
Disasters in BOTH Dataset 1 & 2:       0
Disasters in BOTH Dataset 1 & 3:       14
Disasters in ALL 3 datasets:           0

── SAMPLE DISASTER NUMBERS ──
Dataset 1: ['5529', '5528', '5527', '4312', '4251']
Dataset 2: ['1239', '1239', '1239', '1603', '1239']
Dataset 3: ['3601', '3602', '4899', '1802', '1292']

In [10]:
# Prove the Join Works on Overlapping Records

print("=" * 55)
print("PROVING THE JOIN WORKS")
print("=" * 55)

# Join Dataset 1 & 3 on disasterNumber (14 overlaps exist)
df_joined = pd.merge(
    df_declarations,
    df_summaries,
    on='disasterNumber',
    how='inner'  # Only keep rows that exist in BOTH tables
)

print(f"\nDataset 1 rows:          {len(df_declarations)}")
print(f"Dataset 3 rows:          {len(df_summaries)}")
print(f"Joined result rows:      {len(df_joined)}")
print(f"\n✅ Join works! {len(df_joined)} matching disasters found")

# Show the joined result
print("\n── JOINED DATA PREVIEW ──")
preview_cols = ['disasterNumber', 'state', 'incidentType',
                'declarationDate', 'totalObligatedAmountPa']
display(df_joined[preview_cols].head(10))

=======================================================
PROVING THE JOIN WORKS
=======================================================

Dataset 1 rows:          200
Dataset 3 rows:          200
Joined result rows:      15

✅ Join works! 15 matching disasters found

── JOINED DATA PREVIEW ──

,disasterNumber,state,incidentType,declarationDate,totalObligatedAmountPa
0,5492,NM,Fire,2024-05-26T00:00:00.000Z,NaN
1,5470,WA,Fire,2023-07-23T00:00:00.000Z,NaN
2,5468,WA,Fire,2023-07-05T00:00:00.000Z,NaN
3,5467,WA,Fire,2023-07-03T00:00:00.000Z,NaN
4,5463,KS,Fire,2023-04-13T00:00:00.000Z,247922.91
5,5460,OK,Fire,2023-03-31T00:00:00.000Z,208241.86
6,5456,WA,Fire,2022-10-17T00:00:00.000Z,NaN
7,5456,WA,Fire,2022-10-17T00:00:00.000Z,NaN
8,5451,CA,Fire,2022-09-06T00:00:00.000Z,23815278.46
9,5421,OK,Fire,2021-12-15T00:00:00.000Z,195815.29

In [13]:
# Summary Documentation

print("=" * 18)
print("FINDINGS SUMMARY")
print("=" * 18)

summary = {

    "Dataset 1 — DisasterDeclarationsSummaries": {
        "rows_sampled"    : len(df_declarations),
        "total_columns"   : len(df_declarations.columns),
        "join_key"        : "disasterNumber (int64 → converted to string)",
        "key_columns"     : ["disasterNumber", "state", "incidentType",
                             "declarationDate", "incidentBeginDate",
                             "incidentEndDate", "declarationType"],
        "nulls_to_handle" : ["incidentEndDate (38)", "disasterCloseoutDate (159)",
                             "lastIAFilingDate (200% — DROP)"],
        "purpose"         : "Core disaster metadata — who, what, when, where"
    },

    "Dataset 2 — PublicAssistanceFundedProjectsDetails": {
        "rows_sampled"    : len(df_pa),
        "total_columns"   : len(df_pa.columns),
        "join_key"        : "disasterNumber (int64 → converted to string)",
        "key_columns"     : ["disasterNumber", "stateAbbreviation",
                             "incidentType", "totalObligated",
                             "federalShareObligated", "damageCategoryDescrip"],
        "target_variable" : "SUM of totalObligated per disasterNumber",
        "nulls_to_handle" : ["county (10) — minor, will drop column"],
        "purpose"         : "Project-level funding — SOURCE OF TARGET VARIABLE"
    },

    "Dataset 3 — FemaWebDisasterSummaries": {
        "rows_sampled"    : len(df_summaries),
        "total_columns"   : len(df_summaries.columns),
        "join_key"        : "disasterNumber (int64 → converted to string)",
        "key_columns"     : ["disasterNumber", "totalObligatedAmountPa",
                             "totalObligatedAmountCatAb",
                             "totalObligatedAmountHmgp"],
        "columns_to_drop" : ["totalNumberIaApproved", "totalAmountIhpApproved",
                             "totalAmountHaApproved", "totalAmountOnaApproved",
                             "iaLoadDate — ALL 100% null"],
        "purpose"         : "Pre-aggregated totals — CROSS-VALIDATION of our aggregation"
    },

    "Join Strategy": {
        "key"             : "disasterNumber",
        "ds1_ds2_overlap" : "0 in sample — expected, different time periods fetched",
        "ds1_ds3_overlap" : "14 confirmed working joins",
        "full_data"       : "Overlaps will be massive when full dataset fetched in Day 3",
        "type_issue"      : "All int64 — standardise to string before joining"
    }
}

for dataset, info in summary.items():
    print(f"\n{'=' * 55}")
    print(f"📊 {dataset}")
    for key, value in info.items():
        print(f"   {key}: {value}")

==================
FINDINGS SUMMARY
==================

=======================================================
📊 Dataset 1 — DisasterDeclarationsSummaries
   rows_sampled: 200
   total_columns: 28
   join_key: disasterNumber (int64 → converted to string)
   key_columns: ['disasterNumber', 'state', 'incidentType', 'declarationDate', 'incidentBeginDate', 'incidentEndDate', 'declarationType']
   nulls_to_handle: ['incidentEndDate (38)', 'disasterCloseoutDate (159)', 'lastIAFilingDate (200% — DROP)']
   purpose: Core disaster metadata — who, what, when, where

=======================================================
📊 Dataset 2 — PublicAssistanceFundedProjectsDetails
   rows_sampled: 200
   total_columns: 25
   join_key: disasterNumber (int64 → converted to string)
   key_columns: ['disasterNumber', 'stateAbbreviation', 'incidentType', 'totalObligated', 'federalShareObligated', 'damageCategoryDescrip']
   target_variable: SUM of totalObligated per disasterNumber
   nulls_to_handle: ['county (10) — minor, will drop column']
   purpose: Project-level funding — SOURCE OF TARGET VARIABLE

=======================================================
📊 Dataset 3 — FemaWebDisasterSummaries
   rows_sampled: 200
   total_columns: 14
   join_key: disasterNumber (int64 → converted to string)
   key_columns: ['disasterNumber', 'totalObligatedAmountPa', 'totalObligatedAmountCatAb', 'totalObligatedAmountHmgp']
   columns_to_drop: ['totalNumberIaApproved', 'totalAmountIhpApproved', 'totalAmountHaApproved', 'totalAmountOnaApproved', 'iaLoadDate — ALL 100% null']
   purpose: Pre-aggregated totals — CROSS-VALIDATION of our aggregation

=======================================================
📊 Join Strategy
   key: disasterNumber
   ds1_ds2_overlap: 0 in sample — expected, different time periods fetched
   ds1_ds3_overlap: 14 confirmed working joins
   full_data: Overlaps will be massive when full dataset fetched in Day 3
   type_issue: All int64 — standardise to string before joining